version: 2
updates:
- package-ecosystem: npm
  directory: "/web"
  reviewers:
    - "ChrisF999"
  target-branch: "dev"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/server"
  reviewers:
    - "ChrisF999"
  target-branch: "dev"
  schedule:
    interval: daily